server:
  port: 8761  #eureka默认端口号
spring:
  application:
    name: spring-cloud-eurekasingle
eureka:
  client:
    register-with-eureka: false #表示是否将自己注册到eureka 服务上，默认为true，由于我们目前就是要使用它做服务的，故而设为false
    fetch-registry: false  #表示是否从eureka服务上获取注册信息，默认为true，因为这是一个单点的eureka 服务，不需要同步其他eureka服务节点上的数据，故而设为false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。